# The server block contains connection parameters for all connections bot will
# maintain.
[server]

    # Each server has a named section
    [server.rizon]
    # Server hostname
    host = "irc.rizon.net"
    # + prefix indicates a secure connection, lack of prefix an insecure
    # connection.
    port = "+6697"
    # IRC parameters
    nick = "tama"
    user = "tama"
    realname = "tama"
    # Password if the server requires PASS authentication on connect
    # password = ""

    # List of channels to join on connect
    channels = []

        # Servers might use service nickname authentication. If this section is
        # configured, bot will proceed to identify with the given service as
        # soon as RPL_WELCOME is received.
        [server.rizon.service_auth]
        service = "NickServ"  # Defaults to NickServ
        command = "IDENTIFY"  # Defaults to IDENTIFY
        # If a nickserv_username is set, it will be prepended before the given
        # password in the identify command.
        # username = ""
        password = ""

[tama]
# Set command prefix for bot actions
prefix = "."
# Set logging folder
log_folder = "logs"
# Both of these flags may be enabled at the same time, as the raw logging and
# parsed logging write to different files.
# If true, server messages will be logged in their raw state.
log_raw = true
# If true, server messages will be logged in their parsed state.
log_irc = true

# This config is passed directly to python's logging module.
# See: https://docs.python.org/3/library/logging.config.html
# If not set, dictConfig() will never be called as there are no project
# defaults.
[logging]
version = 1

    [logging.formatters]

        [logging.formatters.default]
        format = '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
        datefmt = '%Y-%m-%d %H:%M:%S'

    [logging.handlers]

        [logging.handlers.default]
        class = "logging.StreamHandler"
        formatter = "default"
        level = "INFO"
        stream = "ext://sys.stdout"

    [logging.root]
    level = "INFO"
    handlers = ["default"]
